name: Undroppable_Item
version: 0.0.1
author: Hypex
main: plugin.UndroppableItem
api-version: 1.18
commands:
   undroppable_item:
      description: Plugin command (reload).
      aliases: udi
#      permission: undroppable_item.admin
#      permission-message: You do not have permission <permission>
#      usage: Syntax error! Perhaps you meant /<command> reload?
   set_und_mode:
      description: Sets the mode in which the subject is processed by this plugin.
      aliases: sum
#      permission: undroppable_item.admin
#      permission-message: You do not have permission <permission>
#      usage: Syntax error!
permissions:
   undroppable_item.admin:
      description: Gives access to all commands.
      default: false
   undroppable_item.*:
      description: Gives access to all commands.
      default: false
      children:
         undroppable_item.admin: true